"""
    CyclicBarrier

Synchronization tool used to make a set of tasks wait for each
other to reach a common barrier point in the code.

# Fields

- `n::Int`: number of tasks to wait for.
- `count::Int`: number of tasks that have reached the barrier.
- `cond::Threads.Condition`: trigger to wake up all waiting tasks.
- `generation::Int`: number of times the barrier has been used.
"""
mutable struct CyclicBarrier
    n::Int
    count::Int
    cond::Threads.Condition
    generation::Int
end

# Outer constructor
CyclicBarrier(n::Int) = CyclicBarrier(n, 0, Threads.Condition(), 0)

# Override Base.wait
function wait(x::CyclicBarrier)
    lock(x.cond) do
        gen = x.generation
        x.count += 1
        # The last task to arrive resets the count, increments the generation,
        # and wakes up all waiting tasks
        if x.count == x.n
            x.count = 0
            x.generation += 1
            notify(x.cond)
        # All other tasks wait until the generation number changes
        else
            while gen == x.generation
                wait(x.cond)
            end
        end
    end
end

# Replicate the distribution of a loop's iterations over threads
# done by Julia's built-in static scheduler
function static_loop_split(r::UnitRange{Int}, N::Int, tid::Int)
    len = length(r)
    chunk_size = div(len, N)
    remainder = rem(len, N)
    start_offset = (tid - 1) * chunk_size + min(tid - 1, remainder)
    num_elements = chunk_size + (tid <= remainder ? 1 : 0)
    return (first(r) + start_offset):(first(r) + start_offset + num_elements - 1)
end

# Check if an expression is a call to Threads.@threads
function is_threads_macro(ex::Expr)
    # Check if the expression is a macro call
    ex.head === :macrocall || return false
    # The first argument of a :macrocall is the macro name
    macro_name = ex.args[1]
    # Match against common ways @threads is invoked
    return macro_name === Symbol("@threads") ||
           macro_name == :(Threads.@threads) ||
           macro_name == :(Threads.var"@threads") ||
           macro_name == :(Base.Threads.@threads)
end

# Assemble the lines of code into blocks
function assemble_blocks(x::AbstractVector{Expr})
    mask = is_threads_macro.(x)
    iters = Vector{Expr}(undef, 0)
    blocks = Vector{Vector{Expr}}(undef, 0)
    for i in eachindex(x)
        if mask[i]
            push!(blocks, [x[i]])
            push!(iters, x[i].args[end].args[1].args[2])
        else
            if isempty(blocks) || mask[i-1]
                push!(blocks, [x[i]])
                push!(iters, :())
            else
                push!(blocks[end], x[i])
            end
        end
    end
    return iters, blocks
end

function modify_block(x::AbstractVector{Expr}, i::Int)
    cyclic_barrier = Symbol(:cyclic_barrier_, i)
    if is_threads_macro(x[1])
        loop = x[1].args[end]
        loop_def, loop_body = loop.args
        itr = Symbol(:chunked_indices_, i)
        q = quote
            for $(loop_def.args[1]) in $(itr)[task_id]
                $(loop_body.args...)
            end
            wait($cyclic_barrier)
        end
    else
        q = quote
           if task_id == 1
               $(x...)
           end
           wait($cyclic_barrier)
        end
    end
    Base.remove_linenums!(q)
    return q
end

"""
    @cyclicbarrier ex

This macro modifies the main loop in the `jetcoeffs!` functions generated by `@taylorize`
in order to implement a cyclic barrier that avoids spawning new tasks at every iteration.

!!! warning
    This macro is on an experimental stage; check the integration results carefully.
"""
macro cyclicbarrier(ex)
    # Verify the provided expression is actually a for loop
    @assert ex.head === :for "Expression must be a for loop"
    loop_def, loop_body = ex.args
    # Filter out LineNumberNodes to find the actual code blocks
    lines = map(identity, filter(!Base.Fix2(isa, LineNumberNode), loop_body.args))
    # Assemble the lines of code into blocks
    iters, blocks = assemble_blocks(lines)
    mblocks = modify_block.(blocks, eachindex(blocks))
    body = vcat([b.args for b in mblocks]...)
    # Variable declarations
    names = Symbol.(:cyclic_barrier_, eachindex(mblocks))
    cyclic_barriers = [:($name = CyclicBarrier(Ntasks)) for name in names]
    names = Symbol.(:chunked_indices_, eachindex(iters))
    chunked_indices = [:($name = [static_loop_split($iter, Ntasks, tid) for tid in 1:Ntasks])
        for (name, iter) in zip(names, iters) if iter != :()]
    # Generate the multithreaded code
    # We use esc() to ensure variables resolve in the caller's scope (macro hygiene)
    q = esc(quote
        # Variable declarations
        Ntasks = Threads.threadpoolsize()
        $(cyclic_barriers...)
        $(chunked_indices...)
        function threadsfor_fun(task_id::Int)
            # Reconstruct the original loop
            for $(loop_def.args[1]) in $(loop_def.args[2])
                $(body...)
            end
        end
        # Spawn tasks
        tasks = Vector{Task}(undef, Ntasks)
        for task_id in 1:Ntasks
            tasks[task_id] = Threads.@spawn threadsfor_fun(task_id)
        end
        # Wait for all tasks to complete the entire range of the original loop
        for t in tasks
            fetch(t)
        end
    end)
    Base.remove_linenums!(q)
    return q
end